apiVersion: v1
kind: Service
metadata:
  name: jekyll
  namespace: development

spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 4000
      nodePort: 300097
  selector:
    run: jekyll