apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-deployment
  namespace: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resultapp
  template:
    metadata:
      labels:
        app: resultapp
    spec:
      containers:
      - name: resultapp
        image: kodekloud/examplevotingapp_result:before